# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pwd
    ls
    npm i vuepress
    npm run docs:build
    cd src/.vuepress/dist

    git config --global user.email "choreo-cicd@wso2.com"
    git config --global user.name "Choreo CI Agent"
    git add -A
    git commit -m 'deploy'

    git push  origin  HEAD:gh-pages

  displayName: docs build and publish'
