# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    set -eo pipefail
    pwd
    ls
    npmssd ci
    npm run docs:build
    cp -r src/.vuepress/dist $(Build.ArtifactStagingDirectory) 
    git clean -fd
    git checkout origin/gh-pages
    cp -r $(Build.ArtifactStagingDirectory)/dist/* . 

    git config --global user.email "choreo-cicd@wso2.com"
    git config --global user.name "Choreo CI Agent"

    git add .
    git commit -m 'Updating documentation in $(Build.BuildNumber)'
    git push  origin  HEAD:gh-pages

  displayName: docs build and publish'
